version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: your-app-name
    container_name: your-app-container
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
    ports:
      - "9001:9000" # Changed the host port to 9001

  nginx:
    image: nginx:latest
    container_name: your-nginx-container
    restart: unless-stopped
    ports:
      - "9000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge
