name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: password@123
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2" # Set your PHP version
          extensions: mbstring, mysql, pdo_mysql

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Run Migrations
        run: php artisan migrate

      - name: Run Tests
        run: php artisan test --verbose

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Build the Application
        run: |
          echo "Simulate the build process here"
          # Add additional build steps such as asset compilation if necessary.

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Simulate Deployment
        run: echo "Simulate the deployment process here. For production, set up SSH or cloud deployment scripts."
